# Generated by Django 5.0.1 on 2024-01-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('ContactNo', models.IntegerField(max_length=12)),
                ('Building_Name', models.CharField(max_length=100)),
                ('Flat_No', models.CharField(max_length=100)),
                ('C', models.FloatField()),
                ('B', models.FloatField()),
            ],
        ),
    ]
