# Generated by Django 5.0.1 on 2024-01-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='ContactNo',
            field=models.CharField(max_length=12),
        ),
    ]
